// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NPCIL.DbModels;

namespace NPCIL.Migrations
{
    [DbContext(typeof(NPCIL_DBContext))]
    [Migration("20240731100529_LogSchema")]
    partial class LogSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NPCIL.DbModels.Logs", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<DateTime?>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LogMessage")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("StackTrace")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId")
                        .HasName("PK__Logs__5E5486486551B04B");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblAddMenu", b =>
                {
                    b.Property<int>("MenuSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("menu_sno")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentEng")
                        .HasColumnName("content_eng")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("ContentHind")
                        .HasColumnName("Content_hind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Controller")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("Eventyear")
                        .HasColumnName("eventyear")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("FileEnddate")
                        .HasColumnName("file_Enddate")
                        .HasColumnType("datetime");

                    b.Property<string>("FileImage")
                        .HasColumnName("file_image")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FileStartdate")
                        .HasColumnName("file_Startdate")
                        .HasColumnType("datetime");

                    b.Property<int?>("LinkType")
                        .HasColumnName("linkType")
                        .HasColumnType("int");

                    b.Property<string>("LinkUrlname")
                        .HasColumnName("link_urlname")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("MenuCreatedby")
                        .HasColumnName("menu_createdby")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("MenuCreateddate")
                        .HasColumnName("menu_createddate")
                        .HasColumnType("datetime");

                    b.Property<string>("MenuDescEng")
                        .HasColumnName("menu_desc_eng")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("MenuDescHind")
                        .HasColumnName("menu_desc_hind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuImg")
                        .HasColumnName("menu_img")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("MenuNameEng")
                        .HasColumnName("menu_name_eng")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("MenuNameHind")
                        .HasColumnName("menu_name_hind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MenuOrder")
                        .HasColumnName("menuOrder")
                        .HasColumnType("int");

                    b.Property<int?>("MenuPosition")
                        .HasColumnName("menu_position")
                        .HasColumnType("int");

                    b.Property<int?>("MenuType")
                        .HasColumnName("menu_type")
                        .HasColumnType("int");

                    b.Property<string>("MenuUpdatedby")
                        .HasColumnName("menu_updatedby")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("MenuUpdateddate")
                        .HasColumnName("menu_updateddate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("TabActive")
                        .HasColumnName("tab_active")
                        .HasColumnType("int");

                    b.HasKey("MenuSno");

                    b.ToTable("tbl_AddMenu");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblBanner", b =>
                {
                    b.Property<int>("BanSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ban_sno")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BanAltTag")
                        .HasColumnName("ban_altTag")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("BanAltTagLang")
                        .HasColumnName("ban_altTagLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BanCreatedBy")
                        .HasColumnName("ban_createdBy")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("BanCreatedDate")
                        .HasColumnName("ban_createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("BanLinkUrl")
                        .HasColumnName("ban_linkURL")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("BanTitle")
                        .HasColumnName("ban_title")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("BanTitleLang")
                        .HasColumnName("ban_titleLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BanUpdatedBy")
                        .HasColumnName("ban_updatedBy")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("BanUpdatedDate")
                        .HasColumnName("ban_updatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("BanUploadImg")
                        .HasColumnName("ban_uploadImg")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.HasKey("BanSno");

                    b.ToTable("tbl_Banner");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblCategory", b =>
                {
                    b.Property<int>("CtSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ct_sno")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CtCreatedBy")
                        .HasColumnName("ct_createdBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("CtCreatedDate")
                        .HasColumnName("ct_createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CtName")
                        .HasColumnName("ct_name")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<DateTime?>("CtUpdateDate")
                        .HasColumnName("ct_updateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CtUpdatedBy")
                        .HasColumnName("ct_updatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("CtSno");

                    b.ToTable("tbl_Category");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblContent", b =>
                {
                    b.Property<int>("ConSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("con_sno")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConCreatedBy")
                        .HasColumnName("con_createdBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("ConCreatedDate")
                        .HasColumnName("con_createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ConName")
                        .HasColumnName("con_name")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("ConUpdatedBy")
                        .HasColumnName("con_updatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("ConUpdatedDate")
                        .HasColumnName("con_updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("ConSno");

                    b.ToTable("tbl_Content");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblContentManager", b =>
                {
                    b.Property<int>("CmSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CM_Sno")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CmCreatedby")
                        .HasColumnName("CM_createdby")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("CmCreateddate")
                        .HasColumnName("CM_createddate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CmEnddate")
                        .HasColumnName("CM_enddate")
                        .HasColumnType("datetime");

                    b.Property<string>("CmImage")
                        .HasColumnName("CM_image")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("CmNameEng")
                        .HasColumnName("CM_name_eng")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("CmNameHind")
                        .HasColumnName("CM_name_hind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CmPageContentEng")
                        .HasColumnName("CM_PageContent_eng")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("CmPageContentHind")
                        .HasColumnName("CM_PageContent_hind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CmPosition")
                        .HasColumnName("CM_position")
                        .HasColumnType("int");

                    b.Property<string>("CmShortDescEng")
                        .HasColumnName("CM_shortDescEng")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("CmShortDescHind")
                        .HasColumnName("CM_shortDescHind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CmStartdate")
                        .HasColumnName("CM_startdate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CmType")
                        .HasColumnName("CM_type")
                        .HasColumnType("int");

                    b.Property<string>("CmUpdatedby")
                        .HasColumnName("CM_updatedby")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("CmUpdateddate")
                        .HasColumnName("CM_updateddate")
                        .HasColumnType("datetime");

                    b.Property<int?>("MenuId")
                        .HasColumnName("Menu_Id")
                        .HasColumnType("int");

                    b.HasKey("CmSno");

                    b.ToTable("tbl_ContentManager");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblHorizontalNews", b =>
                {
                    b.Property<int>("HnSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("HN_Sno")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("HnArchivedDate")
                        .HasColumnName("HN_ArchivedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("HnContent")
                        .HasColumnName("HN_Content")
                        .HasColumnType("int");

                    b.Property<string>("HnCreatedBy")
                        .HasColumnName("HN_CreatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("HnCreatedDate")
                        .HasColumnName("HN_CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("HnDescription")
                        .HasColumnName("HN_Description")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<DateTime?>("HnEndDate")
                        .HasColumnName("HN_EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("HnIsArchived")
                        .HasColumnName("HN_IsArchived")
                        .HasColumnType("bit");

                    b.Property<int?>("HnLang")
                        .HasColumnName("HN_Lang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HnStartDate")
                        .HasColumnName("HN_StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("HnTitle")
                        .HasColumnName("HN_Title")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("HnUpdatedBy")
                        .HasColumnName("HN_UpdatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("HnUpdatedDate")
                        .HasColumnName("HN_UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("HnSno");

                    b.ToTable("tbl_HorizontalNews");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblLanguage", b =>
                {
                    b.Property<long>("LangSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lang_sno")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LangCreatedBy")
                        .HasColumnName("lang_createdBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("LangCreatedDate")
                        .HasColumnName("lang_createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LangName")
                        .HasColumnName("lang_name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("LangUpdatedBy")
                        .HasColumnName("lang_updatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("LangUpdatedDate")
                        .HasColumnName("lang_updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("LangSno");

                    b.ToTable("tbl_Language");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblLinkType", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("link_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LinkName")
                        .HasColumnName("link_name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("LinkId");

                    b.ToTable("tbl_linkType");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblMenuPosition", b =>
                {
                    b.Property<long>("MpSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("mp_sno")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MpCreatedBy")
                        .HasColumnName("mp_createdBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("MpCreatedDate")
                        .HasColumnName("mp_createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MpName")
                        .HasColumnName("mp_name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("MpUpdatedBy")
                        .HasColumnName("mp_updatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("MpUpdatedDate")
                        .HasColumnName("mp_updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("MpSno");

                    b.ToTable("tbl_MenuPosition");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblMenuType", b =>
                {
                    b.Property<int>("MtSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("mt_sno")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MtCreatedBy")
                        .HasColumnName("mt_createdBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("MtCreatedDate")
                        .HasColumnName("mt_createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MtName")
                        .HasColumnName("mt_name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("MtUpdatedBy")
                        .HasColumnName("mt_updatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("MtUpdatedDate")
                        .HasColumnName("mt_updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("MtSno");

                    b.ToTable("tbl_MenuType");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblPageName", b =>
                {
                    b.Property<long>("PgnSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pgn_sno")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PgnCreatedBy")
                        .HasColumnName("pgn_createdBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PgnCreatedDate")
                        .HasColumnName("pgn_createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PgnName")
                        .HasColumnName("pgn_name")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("PgnUpdatedBy")
                        .HasColumnName("pgn_updatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PgnUpdatedDate")
                        .HasColumnName("pgn_updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("PgnSno");

                    b.ToTable("tbl_PageName");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblPhotoCategory", b =>
                {
                    b.Property<string>("PhCCreatedBy")
                        .HasColumnName("PhC_CreatedBy")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PhCCreatedDate")
                        .HasColumnName("PhC_CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("PhCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PhC_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PhCTitle")
                        .HasColumnName("PhC_Title")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("PhCUpdatedBy")
                        .HasColumnName("PhC_UpdatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PhCUpdatedDate")
                        .HasColumnName("PhC_UpdatedDate")
                        .HasColumnType("datetime");

                    b.ToTable("tbl_PhotoCategory");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblPhotoGallery", b =>
                {
                    b.Property<int>("PhSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Ph_sno")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PhCategory")
                        .HasColumnName("Ph_category")
                        .HasColumnType("int");

                    b.Property<string>("PhCreatedBy")
                        .HasColumnName("Ph_createdBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PhCreatedDate")
                        .HasColumnName("Ph_createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PhDescription")
                        .HasColumnName("Ph_description")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("PhDescriptionReg")
                        .HasColumnName("Ph_description_reg")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("PhImage")
                        .HasColumnName("Ph_image")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("PhTag")
                        .HasColumnName("Ph_tag")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("PhTagReg")
                        .HasColumnName("Ph_tag_reg")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("PhTitle")
                        .HasColumnName("Ph_title")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("PhTitleReg")
                        .HasColumnName("Ph_title_reg")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("PhUpdatedBy")
                        .HasColumnName("Ph_updatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PhUpdatedDate")
                        .HasColumnName("Ph_updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("PhSno");

                    b.ToTable("tbl_PhotoGallery");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblPressRelease", b =>
                {
                    b.Property<int>("PrSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PR_sno")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PrContent")
                        .HasColumnName("PR_Content")
                        .HasColumnType("int");

                    b.Property<string>("PrCreatedBy")
                        .HasColumnName("PR_CreatedBy")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PrCreatedDate")
                        .HasColumnName("PR_CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("PrEndDate")
                        .HasColumnName("PR_EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PrFileUpload")
                        .HasColumnName("PR_FileUpload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrLanguage")
                        .HasColumnName("PR_Language")
                        .HasColumnType("int");

                    b.Property<string>("PrLinkUrl")
                        .HasColumnName("PR_LinkURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrPageDescription")
                        .HasColumnName("PR_PageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PrStartDate")
                        .HasColumnName("PR_StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PrTitle")
                        .HasColumnName("PR_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrUpdatedBy")
                        .HasColumnName("PR_UpdatedBy")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PrUpdatedDate")
                        .HasColumnName("PR_UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("PrSno");

                    b.ToTable("tbl_PressRelease");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblPublicAwareness", b =>
                {
                    b.Property<int?>("PaContent")
                        .HasColumnName("PA_Content")
                        .HasColumnType("int");

                    b.Property<string>("PaCreatedBy")
                        .HasColumnName("PA_CreatedBy")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PaCreatedDate")
                        .HasColumnName("PA_CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("PaEndDate")
                        .HasColumnName("PA_EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaFileUpload")
                        .HasColumnName("PA_FileUpload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaLanguage")
                        .HasColumnName("PA_Language")
                        .HasColumnType("int");

                    b.Property<string>("PaLinkUrl")
                        .HasColumnName("PA_LinkURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaPageDescription")
                        .HasColumnName("PA_PageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PA_sno")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("PaStartDate")
                        .HasColumnName("PA_StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaTitle")
                        .HasColumnName("PA_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaUpdatedBy")
                        .HasColumnName("PA_UpdatedBy")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PaUpdatedDate")
                        .HasColumnName("PA_UpdatedDate")
                        .HasColumnType("datetime");

                    b.ToTable("tbl_PublicAwareness");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblPublication", b =>
                {
                    b.Property<int>("PubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Pub_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PubAuthorName")
                        .HasColumnName("Pub_AuthorName")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("PubCreatedBy")
                        .HasColumnName("Pub_CreatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PubCreatedDate")
                        .HasColumnName("Pub_CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PubFileUpload")
                        .HasColumnName("Pub_FileUpload")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<int?>("PubLanguage")
                        .HasColumnName("Pub_Language")
                        .HasColumnType("int");

                    b.Property<string>("PubOthers")
                        .HasColumnName("Pub_Others")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("PubTitle")
                        .HasColumnName("Pub_Title")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<int?>("PubType")
                        .HasColumnName("Pub_Type")
                        .HasColumnType("int");

                    b.Property<string>("PubUpdatedBy")
                        .HasColumnName("Pub_UpdatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PubUpdatedDate")
                        .HasColumnName("Pub_UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("PubId");

                    b.ToTable("tbl_Publication");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblPublicationCategories", b =>
                {
                    b.Property<string>("PcAltTag")
                        .HasColumnName("PC_altTag")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("PcAltTagLang")
                        .HasColumnName("PC_altTagLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcCreatedBy")
                        .HasColumnName("PC_createdBy")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PcCreatedDate")
                        .HasColumnName("PC_createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PcLinkUrl")
                        .HasColumnName("PC_linkURL")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<int>("PcSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PC_sno")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PcTitle")
                        .HasColumnName("PC_title")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("PcTitleLang")
                        .HasColumnName("PC_titleLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcUpdatedBy")
                        .HasColumnName("PC_updatedBy")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PcUpdatedDate")
                        .HasColumnName("PC_updatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PcUploadImg")
                        .HasColumnName("PC_uploadImg")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.ToTable("tbl_PublicationCategories");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblPublicationType", b =>
                {
                    b.Property<int>("PtSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pt_sno")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PtCreatedBy")
                        .HasColumnName("pt_createdBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PtCreatedDate")
                        .HasColumnName("pt_createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PtName")
                        .HasColumnName("pt_name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("PtUpdatedBy")
                        .HasColumnName("pt_updatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PtUpdatedDate")
                        .HasColumnName("pt_updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("PtSno");

                    b.ToTable("tbl_PublicationType");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblStatus", b =>
                {
                    b.Property<int>("StSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("st_sno")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StCreatedBy")
                        .HasColumnName("st_createdBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("StCreatedDate")
                        .HasColumnName("st_createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("StName")
                        .HasColumnName("st_name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("StUpdatedBy")
                        .HasColumnName("st_updatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("StUpdatedDate")
                        .HasColumnName("st_updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("StSno");

                    b.ToTable("tbl_Status");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblTender", b =>
                {
                    b.Property<int>("TenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Tender_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("TenderArchivedDate")
                        .HasColumnName("Tender_archived_date")
                        .HasColumnType("datetime");

                    b.Property<string>("TenderBodyEng")
                        .HasColumnName("Tender_body_eng")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("TenderBodyHindi")
                        .HasColumnName("Tender_body_hindi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderCost")
                        .HasColumnName("Tender_cost")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TenderCreatedDate")
                        .HasColumnName("Tender_CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TenderCreatedby")
                        .HasColumnName("Tender_Createdby")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TenderDateOpening")
                        .HasColumnName("Tender_DateOpening")
                        .HasColumnType("datetime");

                    b.Property<string>("TenderEmd")
                        .HasColumnName("Tender_EMD")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TenderEndDateReceivingTender")
                        .HasColumnName("Tender_EndDate_ReceivingTender")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TenderEndDateSellingTender")
                        .HasColumnName("Tender_EndDate_SellingTender")
                        .HasColumnType("datetime");

                    b.Property<bool?>("TenderIsArchived")
                        .HasColumnName("Tender_IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool?>("TenderMarkImportant")
                        .HasColumnName("Tender_markImportant")
                        .HasColumnType("bit");

                    b.Property<int?>("TenderPosition")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TenderPrebidDate")
                        .HasColumnName("Tender_Prebid_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("TenderScopeEng")
                        .HasColumnName("Tender_Scope_eng")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("TenderScopeHindi")
                        .HasColumnName("Tender_Scope_hindi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TenderStartDateReceivingTender")
                        .HasColumnName("Tender_StartDate_ReceivingTender")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TenderStartDateSellingTender")
                        .HasColumnName("Tender_StartDate_SellingTender")
                        .HasColumnType("datetime");

                    b.Property<int?>("TenderType")
                        .HasColumnType("int");

                    b.Property<string>("TenderUpdatedBy")
                        .HasColumnName("Tender_UpdatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TenderUpdatedDate")
                        .HasColumnName("Tender_UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TenderUpload")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("TenderUrl")
                        .HasColumnName("TenderURL")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("TendorIssuingAuthEng")
                        .HasColumnName("Tendor_IssuingAuth_eng")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("TendorIssuingAuthHindi")
                        .HasColumnName("Tendor_IssuingAuth_hindi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TendorNo")
                        .HasColumnName("Tendor_no")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("TenderId");

                    b.ToTable("Tbl_Tender");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblTenderPosition", b =>
                {
                    b.Property<string>("TpCreatedBy")
                        .HasColumnName("TP_CreatedBy")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("TpCreatedDate")
                        .HasColumnName("TP_CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("TpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TP_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TpTitle")
                        .HasColumnName("TP_Title")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("TpUpdatedBy")
                        .HasColumnName("TP_UpdatedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("TpUpdatedDate")
                        .HasColumnName("TP_UpdatedDate")
                        .HasColumnType("datetime");

                    b.ToTable("tbl_TenderPosition");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblTenderType", b =>
                {
                    b.Property<string>("TtCreatedBy")
                        .HasColumnName("TT_CreatedBy")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TtCreatedDate")
                        .HasColumnName("TT_CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("TtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TT_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TtTitle")
                        .HasColumnName("TT_Title")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("TtUpdatedBy")
                        .HasColumnName("TT_UpdatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TtUpdatedDate")
                        .HasColumnName("TT_UpdatedDate")
                        .HasColumnType("datetime");

                    b.ToTable("tbl_TenderType");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblUserLogin", b =>
                {
                    b.Property<int>("LoginSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Login_sno")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LoginId")
                        .HasColumnName("Login_id")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("LoginName")
                        .HasColumnName("Login_Name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("LoginPassword")
                        .HasColumnName("Login_Password")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<bool?>("LoginStatus")
                        .HasColumnName("Login_Status")
                        .HasColumnType("bit");

                    b.Property<string>("LoginUserName")
                        .HasColumnName("Login_UserName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("LoginSno");

                    b.ToTable("tbl_UserLogin");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblUserMaster", b =>
                {
                    b.Property<long>("UsrSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("usr_sno")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("UseStatus")
                        .HasColumnName("use_status")
                        .HasColumnType("int");

                    b.Property<string>("UsrCreatedBy")
                        .HasColumnName("usr_createdBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("UsrCreatedDate")
                        .HasColumnName("usr_createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UsrEmail")
                        .HasColumnName("usr_email")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UsrName")
                        .HasColumnName("usr_name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UsrPass")
                        .HasColumnName("usr_pass")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UsrPhone")
                        .HasColumnName("usr_phone")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("UsrUpdatedBy")
                        .HasColumnName("usr_updatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("UsrUpdatedDate")
                        .HasColumnName("usr_updatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UsrUserId")
                        .HasColumnName("usr_userId")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UsrUsertype")
                        .HasColumnName("usr_usertype")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("UsrSno");

                    b.ToTable("tbl_User_Master");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblVerticalNews", b =>
                {
                    b.Property<bool?>("VNIsArchived")
                        .HasColumnName("vN_IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("VnArchivedDate")
                        .HasColumnName("VN_ArchivedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("VnContent")
                        .HasColumnName("VN_Content")
                        .HasColumnType("int");

                    b.Property<string>("VnCreatedBy")
                        .HasColumnName("VN_CreatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("VnCreatedDate")
                        .HasColumnName("VN_CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("VnDescription")
                        .HasColumnName("VN_Description")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<DateTime?>("VnEndDate")
                        .HasColumnName("VN_EndDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("VnLang")
                        .HasColumnName("VN_Lang")
                        .HasColumnType("int");

                    b.Property<int>("VnSno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("VN_Sno")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("VnStartDate")
                        .HasColumnName("VN_StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("VnTitle")
                        .HasColumnName("VN_Title")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("VnUpdatedBy")
                        .HasColumnName("VN_UpdatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("VnUpdatedDate")
                        .HasColumnName("VN_UpdatedDate")
                        .HasColumnType("datetime");

                    b.ToTable("tbl_VerticalNews");
                });

            modelBuilder.Entity("NPCIL.DbModels.TblVideoCategory", b =>
                {
                    b.Property<int>("VcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("VC_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("VcCreatedBy")
                        .HasColumnName("VC_CreatedBy")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<DateTime?>("VcCreatedDate")
                        .HasColumnName("VC_CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("VcTitle")
                        .HasColumnName("VC_Title")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("VcUpdatedBy")
                        .HasColumnName("VC_UpdatedBy")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("VcUpdatedDate")
                        .HasColumnName("VC_UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("VcId");

                    b.ToTable("tbl_VideoCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
